# read scala 0 sensor MD to automate light
- alias: "Turn on scala 0 top"
  trigger:
    platform: state
    entity_id: binary_sensor.scala_0_top_md
    to: 'on'
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.scala_0_light

- alias: "Turn off scala 0 top"
  trigger:
    platform: state
    entity_id: binary_sensor.scala_0_top_md
    to: 'off'
  condition: []
  action:
    - service: light.turn_off
      entity_id: light.scala_0_light

- alias: "Turn on scala 0 bottom"
  trigger:
    platform: state
    entity_id: binary_sensor.scala_0_bottom_md
    to: 'on'
  condition: []
  action:
    - service: light.turn_on
      entity_id: light.scala_0_light

- alias: "Turn off scala 0 bottom"
  trigger:
    platform: state
    entity_id: binary_sensor.scala_0_bottom_md
    to: 'off'
  condition: []
  action:
    - service: light.turn_off
      entity_id: light.scala_0_light
    

# When nobody at home or is day light... do not keep light on too long it is useless
- alias: "Nobody Home scala 0 "
  trigger:
    platform: state
    entity_id: light.scala_0_light
    to: 'on'
    for:
      seconds: "1" 
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.out_of_home
        state: 'on'
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.scala_0_light


- alias: "Turn off scala 0 Time to sleep"
  trigger:
    platform: state
    entity_id: light.scala_0_light
    to: 'on'
    for:
      seconds: "100" 
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.time_to_sleep
        state: 'on'
  action:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.scala_0_light
