homeassistant:
  enabled: true
advanced:
  network_key:
    - 71
    - 219
    - 21
    - 10
    - 235
    - 98
    - 134
    - 74
    - 253
    - 173
    - 143
    - 67
    - 23
    - 218
    - 111
    - 139
  pan_id: 63349
  ext_pan_id:
    - 90
    - 81
    - 79
    - 224
    - 79
    - 2
    - 143
    - 88
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.1.2:1883
  user: mqttUser
  password: mqttUser
serial:
  port: /dev/ttyUSB0
frontend:
  enabled: true
  port: 8099
device_options: {}
devices: devices.yaml
availability:
  enabled: true
  active:
    timeout: 10
  passive:
    timeout: 1500
version: 3
